
influxdb:
    image: influxdb:alpine
    expose:
        - 8086
    volumes:
        - "./influxdb:/var/lib/influxdb"
    ports:
        - 8086:8086

grafana:
    build: ./grafana
    links:
        - influxdb:influxdb
    volumes:
        - "./grafana/db:/var/lib/grafana"
        - "./grafana/etc:/etc/grafana"
    ports:
        - 3000:3000

broker:
    build: ./broker
    links:
        - influxdb:influxdb
    ports:
        - 5683:5683